FROM ubuntu:22.04

RUN	apt-get -y update
RUN apt-get install -y openjdk-17-jdk

# run application
WORKDIR /home/ubuntu
COPY /build/libs/getsbee-0.0.1-SNAPSHOT.jar app.jar
COPY /.env-develop .env-develop

EXPOSE 8080

ENTRYPOINT ["java", "-Dspring.profiles.active=develop", "-jar", "app.jar"]